# Alpha 是內測階段，當features/* 或是 bugfix/*分支，使用pull request 方式合到release/*時，打包Alpha進行部署並通知QAteam測試
name: Alpha  # 工作流程的名稱

on:               # 觸發條件
  pull_request:   # 當有 pull_request 事件時觸發
    branches:     # 僅針對特定分支
    - releases/**
    - bugfixes/**
    types:
    - closed      # PR 關閉才會執行

jobs:

  version:  # 工作名稱
    uses: ./.github/workflows/tag-alpha.yaml
    permissions:
      contents: write
    secrets: inherit

  build:
    if: github.event.pull_request.merged == true
    needs: version
    uses: ./.github/workflows/packages-pnpm.yaml
    permissions:
      contents: read  # This is required for actions/checkout
      packages: write # This is required for publish package to github package
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}
